[package]
name = "mylinalg"
version = "0.1.0"
edition = "2021"

[lib]
name = "mylinalg"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/bin.rs"

[[bench]]
name = "my_benchmarks"
harness = false

[dependencies]
rand = "0.8.5"
rayon = "1.7.0"

[dev-dependencies]
criterion = "0.5.1"